### ISSUE TITLE
some hooks Could not be used

### ISSUE THREAD

**Issue by nbsky** [chriskacerguis/codeigniter-restserver#502] opened 2015-07-16 14:50 UTC
'post_controller' ,'display_override' ,'cache_override' ,'post_system'
these hooks  Could not be used  ,i find ’system/core/CodeIgniter.php‘ file could not be executed until the last line when view extend REST_Controller。

**Comment by softwarespot** [comment] 2015-07-16 15:58
Is this a REST_Controller issue? Has it just happened? Do you have a short re-producer?

**Comment by nbsky** [comment] 2015-07-17 02:36
this  Is a REST_Controller issue。Always happen just follow codeigniter tutorial 。https://ellislab.com/codeigniter/user-guide/general/hooks.html

  hooks is ok When access codeigniter Controller,but REST_Controller  'post_controller' ,'display_override' ,'cache_override' ,'post_system' Could not be used. my codeigniter verision is
3.0.0  。and REST_Controller i  Try a number of versions including the latest edition  ,Have this problem。

**Comment by ivantcholakov** [comment] 2015-07-17 11:50
The method REST_Controller::response() scratches my eyes, I am not sure whether this is a completely separate issue.

The method response does not use CodeIgniter's output buffer, but at its end echoes the result directly. To demonstrate what I seek as a result here I am placing a sample code for an ordinary AJAX controller:

```php
<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Sp_map_ajax_controller extends Core_Controller { // My stuff, not important here.

    public function __construct() {

        parent::__construct();

        if (!$this->input->is_ajax_request()) {
            exit(EXIT_ERROR);
        }
    }

    public function index() {

        $this->output->set_header('Content-Type: application/json; charset=utf-8');
        $this->load->model('map');
        $this->output->set_output(json_encode($this->map->guess($this->input->post())));
    }

}
```

You can see usage of $this->output->set_header(...) and $this->output->set_output(...). I think this practice should be adopted for the whole REST controller and its examples. On one example I saw a direct output of var_dump, this is not good IMO.

The point is, let the framework choose the moment to output the result, and maybe the reported issue here about the hooks would be resolved automatically. Maybe, I can not test this.

**Comment by softwarespot** [comment] 2015-07-17 12:58
Makes sense.

**Comment by softwarespot** [comment] 2015-07-17 13:15
Try this please...

```
    /**
     * Takes mixed data and optionally a status code, then creates the response
     *
     * @access public
     * @param array|NULL $data Data to output to the user
     * @param int|NULL $http_code HTTP status code
     * @param bool $continue TRUE to flush the response to the client and continue
     * running the script; otherwise, exit
     */
    public function response($data = NULL, $http_code = NULL, $continue = FALSE)
    {
        // If the HTTP status is not NULL, then cast as an integer
        if ($http_code !== NULL)
        {
            // So as to be safe later on in the process
            $http_code = (int) $http_code;
        }

        // Set the output as NULL by default
        $output = NULL;

        // If data is NULL and no HTTP status code provided, then display, error and exit
        if ($data === NULL && $http_code === NULL)
        {
            $http_code = self::HTTP_NOT_FOUND;
        }

        // If data is not NULL and a HTTP status code provided, then continue
        else if ($data !== NULL)
        {
            // Is compression enabled and available?
            if ($this->config->item('compress_output') === TRUE && $this->_zlib_oc == FALSE)
            {
                if (extension_loaded('zlib'))
                {
                    $http_encoding = $this->input->server('HTTP_ACCEPT_ENCODING');
                    if ($http_encoding !== NULL && strpos($http_encoding, 'gzip') !== FALSE)
                    {
                        ob_start('ob_gzhandler');
                    }
                }
            }

            // If the format method exists, call and return the output in that format
            if (method_exists($this->format, 'to_' . $this->response->format))
            {
                // Set the format header
                $this->output->set_content_type($this->_supported_formats[$this->response->format], strtolower($this->config->item('charset')));

                $output = $this->format->factory($data)->{'to_' . $this->response->format}();

                // An array must be parsed as a string, so as not to cause an array to string error.
                // Json is the most appropriate form for such a datatype
                if ($this->response->format === 'array')
                {
                    $output = $this->format->factory($output)->{'to_json'}();
                }
            }
            else
            {
                // If an array or object, then parse as a json, so as to be a 'string'
                if (is_array($data) || is_object($data))
                {
                    $data = $this->format->factory($data)->{'to_json'}();
                }

                // Format is not supported, so output the raw data as a string
                $output = $data;
            }
        }

        // If not greater than zero, then set the HTTP status code as 200 by default
        // Though perhaps 500 should be set instead, for the developer not passing a
        // correct HTTP status code
        $http_code > 0 || $http_code = self::HTTP_OK;

        $this->output->set_status_header($http_code);

        // JC: Log response code only if rest logging enabled
        if ($this->config->item('rest_enable_logging') === TRUE)
        {
            $this->_log_response_code($http_code);
        }

        // If zlib.output_compression is enabled it will compress the output,
        // but it will not modify the content-length header to compensate for
        // the reduction, causing the browser to hang waiting for more data.
        // We'll just skip content-length in those cases
        if (!$this->_zlib_oc && !$this->config->item('compress_output'))
        {
            $this->output->set_header('Content-Length: ' . strlen($output));
        }
        
        // Output the data
        $this->output->set_output($output);

        if ($continue === FALSE)
        {
            // Display the data and exit execution
            $this->output->_display();
            exit;
        }
        
        // Otherwise dump the output automatically
    }
```

**Comment by ivantcholakov** [comment] 2015-07-17 17:05
@softwarespot

Looks interesting, I tried it.

Something unclear I saw about:

```php
            // Is compression enabled and available?
            if ($this->config->item('compress_output') === TRUE && $this->_zlib_oc == FALSE)
            {
                if (extension_loaded('zlib'))
                {
                    $http_encoding = $this->input->server('HTTP_ACCEPT_ENCODING');
                    if ($http_encoding !== NULL && strpos($http_encoding, 'gzip') !== FALSE)
                    {
                        ob_start('ob_gzhandler');
                    }
                }
            }
```

Within $this->output->_display(); there is something about ob_start('ob_gzhandler'); A duplication?

-------------------------------------------------------

@nbsky

I got it, it is by design. :-)

See the signature of the method response:

```php
public function response($data = NULL, $http_code = NULL, $continue = FALSE)
```

When the parameter $continue is FALSE, at the end of the method response() exit statement is executed and the hooks that you mentioned could not be triggered.

Why it has been decided this way, I don't know. Any suggestions are welcome.

Meanwhile $continue = TRUE will make the hooks accessible.

**Comment by ivantcholakov** [comment] 2015-07-17 17:50
```php
public function prepare_response($data = NULL, $http_code = NULL)
{
    $this->response($data, $http_code, FALSE);
}
```

This is the way for having the "post_" hooks and keeping BC. A only need a shorter and expressive name for this new method.

**Comment by softwarespot** [comment] 2015-07-17 18:31
I have felt that $continue was somewhat confusing. I would have used $exit instead and set to default TRUE. As for ob_start('ob_gzhandler'); I have no clue right now as to this affects CI3's output library.

**Comment by ivantcholakov** [comment] 2015-07-18 19:54
@softwarespot

The problem is with the default value, it makes the "post_" hooks inactive by default and this is surprising. I still think that an additional method is required, the response() signature is to stay as it is for BC. I came up to a "CodeIgniter style" name set_response():

```php
public function set_response($data = NULL, $http_code = NULL)
{
    // The following line tells what is to be done here.
    // In order not to pass $data twice as an argument,
    // the necessary fragments of code might be written
    // again here. Ugly, yes.
    $this->response($data, $http_code, TRUE);
}
```

The name set_response is shorter and gives the idea that output is delayed.

**Comment by ivantcholakov** [comment] 2015-07-18 20:18
Another small detail about the output buffer usage, at the initialization of the REST_Controller I would place the following statement:

```php
$this->output->parse_exec_vars = FALSE;
```
 so the output not to be corrupted by accident.

I am going to summarize the thoughts here and to make experimental commits in my place.

**Comment by ivantcholakov** [comment] 2015-07-19 04:00
For the moment this is what I've got:
https://github.com/ivantcholakov/starter-public-edition-3/commit/59b8fc09680fd649d03e67da7595d903d2717c2e
https://github.com/ivantcholakov/starter-public-edition-3/commit/32e30bcfb06d153fde7a4e8874ffb48d7fb08bf9
https://github.com/ivantcholakov/starter-public-edition-3/commit/93f7c03f2f17b311615a6b195cc6fc87719744c1

**Comment by ivantcholakov** [comment] 2015-07-19 05:45
Ok, this is a draft for changes, a material for thinking and comments.

**Comment by softwarespot** [comment] 2015-07-19 06:13
I like the debug preview, though feel it's out of scope for this library. I am also not too keen on the use of @ in general. As for the changes, I am happy with:

https://github.com/ivantcholakov/starter-public-edition-3/commit/59b8fc09680fd649d03e67da7595d903d2717c2e
https://github.com/ivantcholakov/starter-public-edition-3/commit/32e30bcfb06d153fde7a4e8874ffb48d7fb08bf9
https://github.com/ivantcholakov/starter-public-edition-3/commit/93f7c03f2f17b311615a6b195cc6fc87719744c1
https://github.com/ivantcholakov/starter-public-edition-3/commit/c4e4a3acf21e4341184b32593ecfc63603149a51

Also the compress_output config item should be removed from rest.php as well.

**Comment by ivantcholakov** [comment] 2015-07-19 06:33
I don't get the note about 'compress_output'. It is a CodeIgniter setting and it is used by the Output class https://github.com/bcit-ci/CodeIgniter/blob/3.0.0/application/config/config.php#L456

I cleaned its usage in the REST_Controller.

**Comment by softwarespot** [comment] 2015-07-19 07:03
I thought it was in rest.php, sorry about that.

You can prepare the PR if you want? Which is easier?

**Comment by ivantcholakov** [comment] 2015-07-19 07:18
@softwarespot

Better you do the PR. The initial draft is yours, let the contribution be yours too. Pickup the things you like.

**Closed** 2015-07-21 00:46 UTC
