### ISSUE TITLE
Basic auth always valid

### ISSUE THREAD

**Issue by fabio-ravizzotti** [chriskacerguis/codeigniter-restserver#753] opened 2017-01-10 14:44 UTC
Hi,
I think there is a problem on basic authentication in the version 3.0.0 because it results valid with wrong credentials or without them.

I tried to rollback to version 2.8.0 and all it works correctly.

May you check it please?

**Comment by asystat** [comment] 2017-01-13 19:52
Same problem here... basic auth only work for index pages. If I create another public function in the controller, any request goes through

**Comment by chriskacerguis** [comment] 2017-01-20 02:59
Investigating...

**Comment by chriskacerguis** [comment] 2017-01-20 03:26
So, the problem is here: https://github.com/chriskacerguis/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php#L828 

basically, it needs to add the following 2 lines:
```php
$this->output->_display();
exit; 
```
The problem that I am having is that using exit breaks the unit testing, so I'm trying to rework things so I don't have to use exit.

**Comment by amorimtiago** [comment] 2017-01-23 12:09
Hi, 

I'm starting using the restserver, thanks for providing such good tool.

It appears the rest_auth = 'session' method is always validating any request, whether the session exists or not.

While debugging the REST_Controller.php I've found the _check_php_session is actually identifying the lacking of the session and throwing a HTTP_UNAUTHORIZED response, but the process continues and the user method (i.e. "get") always responds as if is validated.

**Comment by mpa2304** [comment] 2017-01-24 16:51
Digest auth, also always valid

**Comment by benyaminshoham** [comment] 2017-01-25 08:47
I suggest that the REST_Controller will not call the endpoint if authentication failed. Aborting the script execution mid-air might have worse implications than breaking tests...

**Comment by zilth** [comment] 2017-03-28 01:34
I found this problem. 
In the REST_Controller.php function _remap (line 629)
$this->response is missing a 'return;' after each unauthorized or forbidden response.
The code keeps going to the next section which eventually becomes authorized.

This has been fixed in other pull requests in a much more complicated way.

**Comment by kalimerre** [comment] 2017-04-10 11:02
Fix comes with this commit https://github.com/chriskacerguis/codeigniter-restserver/commit/54b2b9cf0698811f9fdf3a1f833f94295ef7a955

**Comment by chriskacerguis** [comment] 2017-04-16 21:18
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.

**Closed by chriskacerguis** 2017-04-16 21:18 UTC
Labels: Investigating
