### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by kingrootid** [chriskacerguis/codeigniter-restserver#1044] opened 2019-11-19 03:16 UTC
Message: Class 'REST_Controller' not found (use class Example extends REST_Controller )
Message: Class 'chriskacerguis\RestServer\RestController' not found (use class Example extends RESTController)

**Comment by salmasian** [comment] 2019-11-19 14:53
This can be closed as duplicate of #1042

**Closed** 2019-11-22 23:55 UTC
