### ISSUE TITLE
Error After Upgrade - Commits on Jun 2, 2018

### ISSUE THREAD

**Issue by yudikondo** [chriskacerguis/codeigniter-restserver#930] opened 2018-06-03 17:19 UTC
After upgrade - Commits on Jun 2, 2018

Fatal error: Class 'Restserver\Libraries\CI_Controller' not found in ....\application\libraries\REST_Controller.php on line 22

I've already updated the composer

**Comment by gfiore88** [comment] 2018-06-08 09:07
Same issue here... any ideas?

**Comment by IvanGo82** [comment] 2018-06-08 13:55
just add:
`use CI_Controller;`
at the begin of REST_Controller.php

**Comment by ColorTwist** [comment] 2018-06-08 15:34
Tried, now it says: Message: Class 'REST_Controller' not found

**Comment by IvanGo82** [comment] 2018-06-08 15:44
Add:
require APPPATH . 'libraries/Format.php';

**Comment by luckydonald** [comment] 2018-06-08 19:15
Potential duplicate of #912

**Comment by luckydonald** [comment] 2018-06-08 19:16
@chriskacerguis the switch to that isn't documented.

**Comment by heyjouh96** [comment] 2018-06-12 12:01
Both #912 and this one didn't solve anything. Can someone fix this, please?

**Comment by vrananavare** [comment] 2018-06-13 08:19
after i  use CI_Controller then
"Class 'REST_Controller' not found " this error come

**Comment by Rik0253** [comment] 2018-07-06 07:14
yeh same is here after i "use CI_Controller" in REST_Controller it gives error "Class REST_Controller Not Found".
Any help please

**Comment by EdgarCabral** [comment] 2018-07-07 14:40
Message: Class 'Restserver\Libraries\CI_Controller' not found
Filename: libraries/REST_Controller.php
Line Number: 22

Help me!!!! please

**Comment by cinder92** [comment] 2018-07-15 08:58
same issue here

**Comment by CreatorB** [comment] 2018-07-26 02:17
in your controller api php make sure have this,
```
require APPPATH . '/libraries/REST_Controller.php';
use Restserver\Libraries\REST_Controller;
```

and then go to your Rest_Contreller and make sure you have this
```
use CI_Controller;

require APPPATH . 'libraries/Format.php';
```

Hope that answers your question

**Comment by MusawerAli** [comment] 2019-01-16 16:20
Add This
```
require(APPPATH.'/libraries/REST_Controller.php');
use Restserver\Libraries\REST_Controller;
 use CI_Controller;

require APPPATH . 'libraries/Format.php';
```

**Comment by ajazkhanpathan** [comment] 2019-02-19 07:32
Thanks @CreatorB 
your code is realy work

**Comment by freddy-daniel** [comment] 2019-04-04 07:15
Still no luck

**Comment by freddy-daniel** [comment] 2019-04-04 07:19
```
Fatal error: Class 'Restserver\Libraries\Format' not found in E:\web-service\application\libraries\REST_Controller.php on line 865
A PHP Error was encountered
Severity: Error

Message: Class 'Restserver\Libraries\Format' not found

Filename: libraries/REST_Controller.php

Line Number: 865

Backtrace:
```

**Comment by T3RON** [comment] 2019-06-07 12:02
> ```
> Fatal error: Class 'Restserver\Libraries\Format' not found in E:\web-service\application\libraries\REST_Controller.php on line 865
> A PHP Error was encountered
> Severity: Error
> 
> Message: Class 'Restserver\Libraries\Format' not found
> 
> Filename: libraries/REST_Controller.php
> 
> Line Number: 865
> 
> Backtrace:
> ```

i have same error

**Comment by hudi1212** [comment] 2019-07-02 01:30
i have problem 

`A PHP Error was encountered
Severity: Compile Error

Message: Class Example cannot extend from trait Restserver\Libraries\REST_Controller

Filename: api/Example.php

Line Number: 22

Backtrace:`

**Comment by abanghendri** [comment] 2019-07-29 03:44
> 
> 
> i have problem. how to fix it??
> 
> `A PHP Error was encountered
> Severity: Compile Error
> 
> Message: Class Example cannot extend from trait Restserver\Libraries\REST_Controller
> 
> Filename: api/Example.php
> 
> Line Number: 22
> 
> Backtrace:`

same problem, please help me urgent

**Comment by Jupriadi** [comment] 2019-08-01 12:28
> i have problem. how to fix it??
> 
> `A PHP Error was encountered
> Severity: Compile Error
> 
> Message: Class Example cannot extend from trait Restserver\Libraries\REST_Controller
> 
> Filename: api/Example.php
> 
> Line Number: 22
> 
> Backtrace:`

i did it too. and i have no solution..

**Comment by Jupriadi** [comment] 2019-08-01 13:34
yess.. i've solved my problem.. i use this

application\libraries\REST_Controller.php

Add require APPPATH . 'libraries/REST_Controller_Definitions.php'; just before trait REST_Controller {
require APPPATH . 'libraries/REST_Controller_Definitions.php';

trait REST_Controller {
application\controllers\api\Example.php

class Example extends CI_Controller { instead of class Example extends REST_Controller {
Place use REST_Controller { REST_Controller::__construct as private __resTraitConstruct; } as the first line after class Example extends CI_Controller {
Add parent::__construct(); and $this->__resTraitConstruct(); to __construct() function.
Change all response methods to HTTP response code instead of constants. For example $this->response($users, 200); instead of $this->response($users, REST_Controller::HTTP_OK);

**Comment by CarlosPinedaT** [comment] 2019-08-05 02:23
After several attempts without any good results ... I finally got my controller to respond properly:

This is my controller

`
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/REST_Controller_Definitions.php';
use Restserver\Libraries\REST_Controller;

require APPPATH . 'libraries/Format.php';

class Api extends CI_Controller
{

    use REST_Controller {
        REST_Controller::__construct as private __resTraitConstruct;
    }

    public function ini_get()
    {
        $data = array(
            'version' => '0.1'
        );

        $this->response($data, 200);
    }
}
`

**Comment by chriskacerguis** [comment] 2019-11-13 00:30
This should be working with the latest release.

**Closed by chriskacerguis** 2019-11-13 00:30 UTC

**Comment by luckydonald** [comment] 2019-11-13 00:32
> latest release
29d10878cacda817d15bd9cf639dc71ae8485663

**Comment by chriskacerguis** [comment] 2019-11-13 00:33
https://github.com/chriskacerguis/codeigniter-restserver/releases/tag/3.1.1
