### ISSUE TITLE
Notice: Array to string conversion (libraries/REST_Controller.php:523)

### ISSUE THREAD

**Issue by 3hertz** [chriskacerguis/codeigniter-restserver#445] opened 2015-04-28 12:57 UTC
A PHP Error was encountered

Severity: Notice

Message: Array to string conversion

Filename: libraries/REST_Controller.php

Line Number: 523

Backtrace:

File: /var/www/html/siteroot/application/libraries/REST_Controller.php
Line: 523
Function: _error_handler

File: /var/www/html/siteroot/application/controllers/Api.php
Line: 39
Function: response

File: /var/www/html/siteroot/application/libraries/REST_Controller.php
Line: 437
Function: call_user_func_array

File: /var/www/html/siteroot/application/libraries/REST_Controller.php
Line: 423
Function: _fire_method

File: /var/www/html/siteroot/index.php
Line: 295
Function: require_once

----------------------

"Format" class is not used.

**Comment by 3hertz** [comment] 2015-04-28 13:18
"Format" class is not used.

**Comment by chriskacerguis** [comment] 2015-05-06 12:55
Could you please provide a bit more context here?

**Comment by dontforget** [comment] 2015-05-18 10:33
I've the same issue. How to reproduce it ?

Simply visit try format jsonp in request.
Example: /rest/user?format=jsonp&id=1

Thank you.

**Comment by chriskacerguis** [comment] 2015-05-27 14:48
Investigating...

**Comment by ahcheqiu** [comment] 2015-06-17 08:40
line 523: header('Content-Type: ' . $this->_supported_formats[$this->response->format] . '; charset=' . strtolower($this->config->item('charset')));
php will treat $this->response->format and $this->config->item('charset') as string , so var_dump these 2 variables and check which one is an array

**Comment by softwarespot** [comment] 2015-06-28 18:58
Fairly easy to fix! The problem is because there is no to_jsonp() method, which if you want jsonp returned then you need to set a GET variable called callback to your "function" name e.g. ?format=json&callback=my_super_example. OK?

Any way I have fixed you problem, just need to fix this bug! I guess my fix for this ticket, should also fix #468? Lets see.

**Closed** 2015-06-28 20:36 UTC
